config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :proposals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'proposals#index'

  post '/proposal_form_validate/destination', to: 'auto_check#validate_destination',
                                              as: :proposal_form_validate_destination
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/proposal.rb
# frozen_string_literal: true

class Proposal < ApplicationRecord
  validates :source, length: {minimum: 3}
  validates :destination, length: {minimum: 3}
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/auto_check_controller.rb
# frozen_string_literal: true

class AutoCheckController < ApplicationController
  skip_before_action :verify_authenticity_token

  def validate_destination
    destination = params[:value]
    case destination
    when ->(x) { x&.empty? }
      render(
        status: :unprocessable_entity,
        plain: "Cannot be empty",
      )
    when ->(x) { x&.length&.< 3 }
      render(
        status: :unprocessable_entity,
        plain: "Has to be longer than 3 symbols",
      )
    when ->(x) { x&.present? }
      render(
        status: :ok,
        plain: "thanks",
      )
    end
  end
end

app/controllers/proposals_controller.rb
# frozen_string_literal: true

class ProposalsController < ApplicationController
  before_action :set_proposal, only: %i[show edit update destroy]

  # GET /proposals or /proposals.json
  def index
    @proposals = Proposal.all
  end

  # GET /proposals/1 or /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals or /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to proposal_url(@proposal), notice: "Proposal was successfully created." }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1 or /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to proposal_url(@proposal), notice: "Proposal was successfully updated." }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1 or /proposals/1.json
  def destroy
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url, notice: "Proposal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_proposal
    @proposal = Proposal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def proposal_params
    params.require(:proposal).permit(:source, :destination, :source_loading_date, :destination_unloading_date)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/proposals_helper.rb
# frozen_string_literal: true

module ProposalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kek</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag("primer_view_components") %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag("primer_view_components") %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proposals/_form.html.erb
<%= form_with(model: proposal) do |form| %>
  <% if proposal.errors.any? %>
    <%= render(Primer::Alpha::Banner.new(scheme: :danger)) do %>
      <% errors_count_msg = pluralize(proposal.errors.count, "error")%>
      <h2><%= "#{errors_count_msg} prohibited this proposal from being saved:" %></h2>

      <ul>
        <% proposal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>

  <%= primer_form_with(model: proposal) do |f| %>
    <%= render(Proposals::EditForm.new(f)) %>
  <% end %>
<% end %>

app/views/proposals/_proposal.html.erb
<div id="<%= dom_id proposal %>">
  <p>
    <strong>Source:</strong>
    <%= proposal.source %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= proposal.destination %>
  </p>

  <p>
    <strong>Source loading date:</strong>
    <%= proposal.source_loading_date %>
  </p>

  <p>
    <strong>Destination unloading date:</strong>
    <%= proposal.destination_unloading_date %>
  </p>

</div>

app/views/proposals/edit.html.erb
<%= render(Primer::Alpha::Layout.new) do |component| %>
  <% component.with_main(width: :md, p: 6) do %>

    <h1>Editing proposal</h1>

    <%= render "form", proposal: @proposal %>

    <br>

    <div>
      <%= link_to "Show this proposal", @proposal %> |
      <%= link_to "Back to proposals", proposals_path %>
    </div>


  <% end %>
  <% component.with_sidebar %>
<% end %>

app/views/proposals/index.html.erb
<%= render(Primer::Alpha::Layout.new) do |component| %>
  <% component.with_main(width: :md, p: 6) do %>
    <% if notice.present? %>
      <%= render(Primer::Alpha::Banner.new(dismiss_scheme: :remove, scheme: :success)) do |component| %>
        <%= notice %>
      <% end %>
    <% end %>

    <h1>Proposals</h1>

    <div id="proposals">
      <% @proposals.each do |proposal| %>
        <%= render proposal %>
        <p>
          <%= link_to "Show this proposal", proposal %>
        </p>
      <% end %>
    </div>
    <%= link_to "New proposal", new_proposal_path %>
  <% end %>
  <% component.with_sidebar %>
<% end %>

app/views/proposals/new.html.erb
<%= render(Primer::Alpha::Layout.new) do |component| %>
  <% component.with_main(width: :md, p: 6) do %>

    <h1>New proposal</h1>

    <%= render "form", proposal: @proposal %>

    <br>

    <div>
      <%= link_to "Back to proposals", proposals_path %>
    </div>

  <% end %>
  <% component.with_sidebar %>
<% end %>

app/views/proposals/show.html.erb
<%= render(Primer::Alpha::Layout.new) do |component| %>
  <% component.with_main(width: :md, p: 6) do %>

    <% if notice.present? %>
      <%= render(Primer::Alpha::Banner.new(dismiss_scheme: :remove, scheme: :success)) do |component| %>
        <%= notice %>
      <% end %>
    <% end %>

    <%= render @proposal %>

    <div>
      <%= link_to "Edit this proposal", edit_proposal_path(@proposal) %> |
      <%= link_to "Back to proposals", proposals_path %>

      <% button = Custom::Button.new(
        scheme: :default,
        size: :medium,
        block: false,
        align_content: :center,
        tag: :button,
        disabled: false
      ) %>
      <%= button_to "Destroy this proposal", @proposal, method: :delete, class: button.css_classes %>
    </div>

  <% end %>
  <% component.with_sidebar %>
<% end %>